export const FETCH_USERS_START = "FETCH_USERS_START";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
export const ADD_FRIEND = "ADD_FRIEND";
export const REMOVE_FRIEND = "REMOVE_FRIEND";
export const SEARCH_USER = "SEARCH_USER";
export const FETCH_LOCAL_USERS_SUCCESS = "FETCH_LOCAL_USERS_SUCCESS";
